services:
  postgres:
    image: postgres:16-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: crm_dev
      POSTGRES_USER: crm
      POSTGRES_PASSWORD: localdev
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U crm -d crm_dev']
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 5s
      retries: 5

  opensearch:
    image: opensearchproject/opensearch:2
    ports:
      - '9200:9200'
    environment:
      discovery.type: single-node
      plugins.security.disabled: 'true'
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: 'Admin_1234!'
      OPENSEARCH_JAVA_OPTS: '-Xms512m -Xmx512m'
    volumes:
      - osdata:/usr/share/opensearch/data
    healthcheck:
      test: ['CMD-SHELL', 'curl -s http://localhost:9200 >/dev/null || exit 1']
      interval: 10s
      timeout: 5s
      retries: 10

  localstack:
    image: localstack/localstack
    ports:
      - '4566:4566'
    environment:
      SERVICES: s3,ses,sqs
      DEFAULT_REGION: us-east-1
    volumes:
      - lsdata:/var/lib/localstack

  mailpit:
    image: axllent/mailpit
    ports:
      - '8025:8025'
      - '1025:1025'

volumes:
  pgdata:
  osdata:
  lsdata:
